version: "3"
services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "6502:6502"
    command: uvicorn app.main:app --host 0.0.0.0 --port 6502 --reload
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
