[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = "."
testpaths = ["app/tests"]
addopts = "-v --import-mode=importlib"